import { useForm } from 'react-hook-form';
import { useState } from 'react';
import AppLayout from '@/Layouts/AppLayout';
import ScriptGenerator from '@/Components/ScriptGenerator';

export default function UserProfile() {
    const [script, setScript] = useState('');

    const { register, handleSubmit, watch, formState: { errors } } = useForm({
        defaultValues: {
            name: '',
            pool: '',
            sharedUsers: 1,
            rateLimit: '',
            sessionTimeout: ''
        }
    });

    const onSubmit = (data) => {
        // Logic to generate Hotspot User Profile script
        // This is simple enough to keep inside the component for now, or could be moved to MikrotikLogic
        const timestamp = new Date().toLocaleString();
        let generated = `# Generated by X Rebuild on ${timestamp}\n`;
        generated += `# Hotspot User Profile: ${data.name}\n\n`;

        generated += `/ip hotspot user profile\n`;

        let command = `add name="${data.name}"`;

        if (data.pool) command += ` address-pool="${data.pool}"`;
        if (data.sharedUsers) command += ` shared-users=${data.sharedUsers}`;
        if (data.rateLimit) command += ` rate-limit="${data.rateLimit}"`; // e.g. 5M/5M
        if (data.sessionTimeout) command += ` session-timeout=${data.sessionTimeout}`;

        // Standard defaults often used
        command += ` keepalive-timeout=2m status-autorefresh=1m transparent-proxy=yes`;

        generated += command + "\n";

        setScript(generated);
    };

    const UserProfileForm = (
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <div>
                <label className="block text-sm font-medium text-gray-700">Profile Name</label>
                <input
                    {...register("name", { required: "Profile Name is required" })}
                    type="text"
                    placeholder="Guest-5M"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-mikrotik-blue focus:ring-mikrotik-blue sm:text-sm py-2 px-3"
                />
                {errors.name && <span className="text-xs text-red-500">{errors.name.message}</span>}
            </div>

            <div>
                <label className="block text-sm font-medium text-gray-700">Address Pool</label>
                <input
                    {...register("pool")}
                    type="text"
                    placeholder="hs-pool-dhcp"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-mikrotik-blue focus:ring-mikrotik-blue sm:text-sm py-2 px-3"
                />
            </div>

            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700">Shared Users</label>
                    <input
                        {...register("sharedUsers", { min: 1 })}
                        type="number"
                        placeholder="1"
                        className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-mikrotik-blue focus:ring-mikrotik-blue sm:text-sm py-2 px-3"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-700">Session Timeout</label>
                    <input
                        {...register("sessionTimeout")}
                        type="text"
                        placeholder="1h"
                        className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-mikrotik-blue focus:ring-mikrotik-blue sm:text-sm py-2 px-3"
                    />
                </div>
            </div>

            <div>
                <label className="block text-sm font-medium text-gray-700">Rate Limit (Rx/Tx)</label>
                <p className="text-xs text-gray-500 mb-1">Format: Upload/Download [Burst/Burst] [Threshold/Threshold]...</p>
                <input
                    {...register("rateLimit")}
                    type="text"
                    placeholder="5M/10M"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-mikrotik-blue focus:ring-mikrotik-blue sm:text-sm py-2 px-3"
                />
            </div>

            <div className="pt-4">
                <button
                    type="submit"
                    className="w-full inline-flex justify-center items-center px-4 py-3 bg-mikrotik-blue border border-transparent rounded-md font-semibold text-sm text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150"
                >
                    Generate Profile Script
                </button>
            </div>
        </form>
    );

    return (
        <AppLayout>
            <ScriptGenerator
                title="Hotspot User Profile"
                description="Create User Profiles for MikroTik Hotspot with rate limits and timeouts."
                form={UserProfileForm}
                generatedScript={script}
                dataToSave={watch()} // Pass current form data for saving
            />
        </AppLayout>
    );
}
